In [1]:
# pip install torch

In [2]:
import torch
import numpy as np
torch.manual_seed(1234)

In [3]:
# help(torch)

# Tensor
- 스칼라는 하나의 숫자
- 벡터는 배열
- 행렬은 숫자의 2-D 배열
- 텐서는 숫자의 N-D 배열

In [4]:
torch.__version__

'1.13.0+cpu'

In [5]:
# 5행 3열 텐서
def describe(x):
    print(f"타입 : {x.type()}")
    print(f"크기 : {x.size()}")
    print(f"값 : {x}")

In [6]:
describe(torch.Tensor(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[2.4480e-34, 6.3899e-43, 2.4480e-34],
        [6.3899e-43, 2.4512e-34, 6.3899e-43]])


In [7]:
describe(torch.randn(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [8]:
# 1이나 0으로 채워진 Tensor
describe(torch.zeros(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x = torch.ones(2,3)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
describe(x.fill_(5))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [11]:
# 리스트로 만들 수 있음
x = torch.Tensor([
    [1,2],
    [2,4]
])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 2])
값 : tensor([[1., 2.],
        [2., 4.]])


In [12]:
# 넘파이 배열로도 만들 수 있음
npy = np.random.rand(2,3)
print()
describe(torch.Tensor(npy))


타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[0.0720, 0.2737, 0.3513],
        [0.1311, 0.2641, 0.2941]])


In [13]:
# Tensor 타입
x = torch.arange(6).view(2,3)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[0, 1, 2],
        [3, 4, 5]])


In [14]:
x = torch.FloatTensor([
    [1,2,3],
    [4,5,6]
])
x = x.long()
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
x = torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ],
    dtype = torch.int64
)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
x = x.float()
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
x = torch.randn(2,3)
x

tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]])

In [18]:
describe(torch.add(x,x))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[ 0.4619,  1.3862, -0.5337],
        [ 4.3569,  0.2043, -0.5180]])


In [19]:
describe(x+x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[ 0.4619,  1.3862, -0.5337],
        [ 4.3569,  0.2043, -0.5180]])


In [20]:
x = torch.arange(6)
x

tensor([0, 1, 2, 3, 4, 5])

In [21]:
x = x.view(2,3)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[0, 1, 2],
        [3, 4, 5]])


In [22]:
describe(x.view(2,3))

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[0, 1, 2],
        [3, 4, 5]])


In [23]:
describe(torch.transpose(x,0,1))
describe(x.T)

타입 : torch.LongTensor
크기 : torch.Size([3, 2])
값 : tensor([[0, 3],
        [1, 4],
        [2, 5]])
타입 : torch.LongTensor
크기 : torch.Size([3, 2])
값 : tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [24]:
describe(torch.sum(x,axis=0))
describe(torch.sum(x,dim=0))

타입 : torch.LongTensor
크기 : torch.Size([3])
값 : tensor([3, 5, 7])
타입 : torch.LongTensor
크기 : torch.Size([3])
값 : tensor([3, 5, 7])


In [25]:
describe(torch.sum(x,axis=1))
describe(torch.sum(x,dim=1))

타입 : torch.LongTensor
크기 : torch.Size([2])
값 : tensor([ 3, 12])
타입 : torch.LongTensor
크기 : torch.Size([2])
값 : tensor([ 3, 12])


In [26]:
# 슬라이싱 제공
x = torch.arange(6).view(2,3)
describe(x)
describe(x[:2,:2])

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[0, 1, 2],
        [3, 4, 5]])
타입 : torch.LongTensor
크기 : torch.Size([2, 2])
값 : tensor([[0, 1],
        [3, 4]])


In [27]:
idx = torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index = idx))

타입 : torch.LongTensor
크기 : torch.Size([2, 2])
값 : tensor([[0, 2],
        [3, 5]])


In [28]:
# 숫자가 증가되는 벡터를 만들 수 있음
x = torch.arange(0,20)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([20])
값 : tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [29]:
# view -> 텐서의 차원을 변경
print(x.view(1,20))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])


In [30]:
print(x.view(1,-1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])


In [31]:
print(x.view(4,-1))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [32]:
x = torch.arange(12).view(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [33]:
print(x.shape)
print(x.unsqueeze(dim=0).shape)
print(x.unsqueeze(dim=1).shape)
print(x.unsqueeze(dim=2).shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [34]:
t = x.unsqueeze(dim=0)
t.squeeze().shape

torch.Size([3, 4])

In [35]:
x = torch.arange(12).reshape(3,4)
print(x)
print(x.sum(dim=0))  # axis 과 dim은 같은 역할을 함
print(x.sum(dim=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([12, 15, 18, 21])
tensor([ 6, 22, 38])


In [36]:
# index_select
x = torch.arange(9).view(3,3)
print(x)
idx = torch.LongTensor([0,2])
print(torch.index_select(x,index = idx, dim=0))
print(torch.index_select(x,index = idx, dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [6, 7, 8]])
tensor([[0, 2],
        [3, 5],
        [6, 8]])


In [37]:
x = torch.arange(6).view(2,3)
print(x)
print(torch.cat([x,x],dim=0))
print(torch.cat([x,x],dim=1))
print(torch.stack([x,x]))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [38]:
x = torch.arange(6).view(2,3)
print(x)
torch.stack([x,x,x],dim=1)

tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5],
         [3, 4, 5]]])

In [39]:
#  전치행렬
x = torch.arange(12).view(3,4)
print(x)
print(x.T)
print(x.transpose(1,0))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


In [40]:
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size).view(batch_size , seq_size , feature_size)
print(x.shape)
print(x)

torch.Size([3, 4, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])


In [41]:
print(x.transpose(1,0).shape)
print(x.transpose(1,0))

torch.Size([4, 3, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


In [42]:
# permute는 일반화된 전치
batch_size = 3
seq_size = 4
feature_size = 5

x = torch.arange(batch_size * seq_size * feature_size).view(batch_size , seq_size , feature_size)
print(x.shape)
print(x)
print('======================================')
print(f"permute(1,0,2) shape {x.permute(1,0,2).shape}")
print(f"permute(1,0,2) shape {x.permute(1,0,2)}")

torch.Size([3, 4, 5])
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
permute(1,0,2) shape torch.Size([4, 3, 5])
permute(1,0,2) shape tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


In [43]:
# Torch를 이용하여 gradient 계산 가능
torch.randn(2,3)

tensor([[-0.1549, -1.3706, -0.1319],
        [ 0.8848, -0.2611,  0.6104]])

In [44]:
torch.randn(2,3, requires_grad=True)

tensor([[-0.0098, -1.4473, -0.2039],
        [ 0.8738, -0.6816,  0.6339]], requires_grad=True)

In [45]:
x1 = torch.arange(6).view(2,3)
describe(x1)
describe(x1.transpose(1,0))
torch.mm(x1,x1.transpose(1,0))

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : tensor([[0, 1, 2],
        [3, 4, 5]])
타입 : torch.LongTensor
크기 : torch.Size([3, 2])
값 : tensor([[0, 3],
        [1, 4],
        [2, 5]])


tensor([[ 5, 14],
        [14, 50]])

In [46]:
x1 = torch.arange(6).view(2,3).float()
describe(x1)
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)
describe(torch.mm(x1,x2))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : tensor([[0., 1., 2.],
        [3., 4., 5.]])
타입 : torch.FloatTensor
크기 : torch.Size([3, 2])
값 : tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 2])
값 : tensor([[ 3.,  6.],
        [12., 24.]])


In [47]:
x = torch.arange(12).view(3,4).float()
print(x)
x2 = torch.ones(4,2)
x2[:,1] += 1
print(x2)
print(x.mm(x2))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])
tensor([[ 6., 12.],
        [22., 44.],
        [38., 76.]])


In [48]:
# gradient 계산
x = torch.tensor([[2.0,3.0]],requires_grad = True)
print(f"x : {x}")
print("==================================================================")
z = 3*x
print(z)
print(f"z = 3*x : {z}")
print("==================================================================")
loss = z.sum()   # 손실함수는 스칼라 값이 필요하기 때문에 Sum을 이용해서 값을 만들어 줌
print(f"loss = z.sum() : {loss}")
loss.backward()  # 입력에 대한 변화율을 계산함
print(f"loss.backward()를 호출한 후 x.grad : {x.grad}")

x : tensor([[2., 3.]], requires_grad=True)
tensor([[6., 9.]], grad_fn=<MulBackward0>)
z = 3*x : tensor([[6., 9.]], grad_fn=<MulBackward0>)
loss = z.sum() : 15.0
loss.backward()를 호출한 후 x.grad : tensor([[3., 3.]])


In [49]:
# 조건이 있는 Gradient 계산
# x = 1 에서 f(x)의 Gradient 찾기
# f(x) = x>0 -- sin(x)
#          cos(x)

In [50]:
def f(x):
    if(x.data > 0).all():
        return torch.sin(x)
    else:
        return torch.cos(x)

In [51]:
x = torch.tensor([1.0,0.5],requires_grad = True)
y = f(x)
y.sum().backward()
x.grad

tensor([0.5403, 0.8776])

In [52]:
x = torch.tensor([1.0,-1.0],requires_grad = True)
print(x)
y=f(x)
print(y)
y.sum().backward()
print(x.grad)

tensor([ 1., -1.], requires_grad=True)
tensor([0.5403, 0.5403], grad_fn=<CosBackward0>)
tensor([-0.8415,  0.8415])


In [53]:
x = torch.tensor([-0.5,-1.0],requires_grad = True)
print(x)
y=f(x)
print(y)
y.sum().backward()
print(x.grad)

tensor([-0.5000, -1.0000], requires_grad=True)
tensor([0.8776, 0.5403], grad_fn=<CosBackward0>)
tensor([0.4794, 0.8415])


In [54]:
# 원소별로 Boolean(불리언) 연산과 sin 및 cos 계산이 수행되지 않는다.
# 마스킹기법 자주
def f2(x):
    mask = torch.gt(x,0).float()
    return mask*torch.sin(x) + (1-mask)*torch.cos(x)
x = torch.tensor([1.0, -1], requires_grad = True)
y = f2(x)
y.sum().backward()
print(x.grad)

tensor([0.5403, 0.8415])
